-- Insert NBA Teams into the teamsTable
INSERT INTO "teamsTable" (
    "id", 
    "createdAt", 
    "updatedAt", 
    "teamManagerId", 
    "teamId", 
    "leagueIds", 
    "teamName", 
    "teamMetaData", 
    "teamImage", 
    "status", 
    "subStatus", 
    "players", 
    "gamesWon", 
    "gamesLost", 
    "gamesPlayed"
)
VALUES
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'atlanta_hawks', '[]', 'Atlanta Hawks', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'boston_celtics', '[]', 'Boston Celtics', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'brooklyn_nets', '[]', 'Brooklyn Nets', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'charlotte_hornets', '[]', 'Charlotte Hornets', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'chicago_bulls', '[]', 'Chicago Bulls', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'cleveland_cavaliers', '[]', 'Cleveland Cavaliers', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'dallas_mavericks', '[]', 'Dallas Mavericks', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'denver_nuggets', '[]', 'Denver Nuggets', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'detroit_pistons', '[]', 'Detroit Pistons', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'golden_state_warriors', '[]', 'Golden State Warriors', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'houston_rockets', '[]', 'Houston Rockets', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'indiana_pacers', '[]', 'Indiana Pacers', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'los_angeles_clippers', '[]', 'Los Angeles Clippers', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'los_angeles_lakers', '[]', 'Los Angeles Lakers', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'memphis_grizzlies', '[]', 'Memphis Grizzlies', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'miami_heat', '[]', 'Miami Heat', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'milwaukee_bucks', '[]', 'Milwaukee Bucks', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'minnesota_timberwolves', '[]', 'Minnesota Timberwolves', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'new_orleans_pelicans', '[]', 'New Orleans Pelicans', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'new_york_knicks', '[]', 'New York Knicks', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'oklahoma_city_thunder', '[]', 'Oklahoma City Thunder', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'orlando_magic', '[]', 'Orlando Magic', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'philadelphia_76ers', '[]', 'Philadelphia 76ers', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'phoenix_suns', '[]', 'Phoenix Suns', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'portland_trail_blazers', '[]', 'Portland Trail Blazers', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'sacramento_kings', '[]', 'Sacramento Kings', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'san_antonio_spurs', '[]', 'San Antonio Spurs', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'toronto_raptors', '[]', 'Toronto Raptors', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'utah_jazz', '[]', 'Utah Jazz', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0),
    (gen_random_uuid(), now(), now(), 'teammanager-baa0fbd3', 'washington_wizards', '[]', 'Washington Wizards', 
     '{"coach": "", "assistantCoach": null, "teamCaptain": "", "teamManager": "Team Manager One", "contactNumber": "09682006456", "contactEmail": "hulomjosuan@gmail.com"}', 
     NULL, '["New Entry"]', '[]', '[]', 0, 0, 0);
